-- SOCCER_SQL_015
-- STADIUM 에 등록된 운동장 중에서
-- 홈팀이 없는 경기장까지 전부 나오도록
-- 카운트 값은 20
SELECT S.STADIUM_NAME ,S.STADIUM_ID,S.SEAT_COUNT,S.HOMETEAM_ID,T.E_TEAM_NAME
FROM  (SELECT STADIUM_NAME,HOMETEAM_ID,STADIUM_ID,SEAT_COUNT
       FROM STADIUM) S
       FULL OUTER JOIN TEAM T ON T.STADIUM_ID LIKE S.STADIUM_ID
ORDER BY HOMETEAM_ID;       

-- SOCCER_SQL_016
-- 평균키가 인천 유나이티스팀의 평균키 보다 작은 팀의 
-- 팀ID, 팀명, 평균키 추출
SELECT T.TEAM_ID,T.TEAM_NAME,ROUND(AVG(P.HEIGHT),2) 평균키
    FROM (SELECT HEIGHT,TEAM_ID
          FROM PLAYER) P
    JOIN TEAM T ON P.TEAM_ID LIKE T.TEAM_ID
    GROUP BY T.TEAM_ID,T.TEAM_NAME
    HAVING ROUND(AVG(P.HEIGHT),2)<180.51 ;
    
SELECT T.TEAM_ID,T.TEAM_NAME,(SELECT ROUND(AVG(HEIGHT),2)
                              FROM PLAYER P
                              WHERE T.TEAM_ID=P.TEAM_ID) 평균키
FROM TEAM T;
                               

    
    
-- SOCCER_SQL_017
-- 포지션이 MF 인 선수들의  소속팀명 및 선수명, 백넘버 출력
SELECT POSITION 포지션,TEAM_NAME "소속 팀명",PLAYER_NAME 선수명,BACK_NO 백넘버
FROM (SELECT POSITION,TEAM_ID,BACK_NO,PLAYER_NAME
      FROM PLAYER
      WHERE POSITION LIKE 'MF') P
            JOIN TEAM T ON P.TEAM_ID LIKE T.TEAM_ID
ORDER BY 선수명 ;


-- SOCCER_SQL_018
-- 가장 키큰 선수 5 추출, 오라클, 단 키 값이 없으면 제외
SELECT PLAYER_NAME 선수명,BACK_NO 백넘버,POSITION 포지션,HEIGHT 키
FROM (SELECT PLAYER_NAME,BACK_NO,POSITION,HEIGHT
       FROM PLAYER
       WHERE HEIGHT IS NOT NULL 
       ORDER BY HEIGHT DESC
       ) P
WHERE ROWNUM <= 5;       
       

-- SOCCER_SQL_019
-- 선수 자신이 속한 팀의 평균키보다 작은 선수 정보 출력
SELECT TEAM_NAME 팀명,PLAYER_NAME 선수명,POSITION 포지션,BACK_NO 백넘버,HEIGHT 키
FROM (SELECT PLAYER_NAME,POSITION,BACK_NO,AVG(HEIGHT) ,HEIGHT, TEAM_ID
      FROM PLAYER )P
    JOIN TEAM T ON T.TEAM_ID LIKE P.TEAM_ID
    GROUP BY T.TEAM_ID,T.TEAM_NAME,PLAYER_NAME,POSITION,BACK_NO,HEIGHT
    
     ;
      
  SELECT TEAM_NAME 팀명,PLAYER_NAME 선수명,POSITION 포지션,BACK_NO 백넘버,HEIGHT 키   
  FROM PLAYER P    
  WHERE P.HEIGHT <= (SELECT AVG(P.HEIGHT)
      FROM TEAM
      GROUP BY TEAM_ID);
-- SOCCER_SQL_020
-- 2012년 5월 한달간 경기가 있는 경기장 조회
-- EXISTS 쿼리는 항상 연관쿼리로 상요한다.
-- 또한 아무리 조건을 만족하는 건이 여러 건이라도
-- 조건을 만족하는 1건만 찾으면 추가적인 검색을 진행하지 않는다.

SELECT STADIUM_ID,STADIUM_NAME
FROM STADIUM S
WHERE EXISTS(SELECT 1
      FROM SCHEDULE D
      WHERE D.STADIUM_ID = S.STADIUM_ID AND D.SCHE_DATE BETWEEN '20120501' AND '20120531'
      );
      
      SELECT S.STADIUM_ID,S.STADIUM_NAME,D.SCHE_DATE
      FROM STADIUM S
      JOIN SCHEDULE D ON D.STADIUM_ID = S.STADIUM_ID;